# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            L2n\Bundle\LoginBundle\Entity\User:
                algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
                    entity:
                        class: L2nLoginBundle:User

                        # if you're using multiple entity managers
                        # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager

            logout:
                path:   /logout
                target: /

            remember_me:
                            key:      "%secret%"
                            lifetime: 604800 # 1 week in seconds
                            path:     /
                            # by default, the feature is enabled by checking a
                            # checkbox in the login form (see below), uncomment the
                            # following line to always enable it.
                            #always_remember_me: true


    access_control:
            # require ROLE_ADMIN for /*
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
